# Numpy

[NumPy](https://numpy.org/) это open-source модуль для python, который предоставляет общие математические и числовые операции.

NumPy - один из ключевых модулей в экосистеме Python, в том числе при решении задач машинного обучения и искусственного интеллекта.

NumPy является наследником Numeric и NumArray. Основан NumPy на библиотеке LAPAC, которая написана на Fortran. Когда-то numpy была частью SciPy. Да, это напоминает мыльную оперу.

Мы подробно разбираем особенности библиотеки, так как на работе с ней основаны все остальные библиотеки, работающие с искусственным интеллектом.

Текст урока опирается на небольшой, но полезный [мануал](https://sites.engineering.ucsb.edu/~shell/che210d/numpy.pdf).

## Установка

Если вы используете Google Colab, то numpy уже установлен на виртуальном сервере и вы можете им пользоваться.

Если вы открыли собственный ноутбук, то можете воспользоваться командой установки, записанной через восклицательный знак


```
!comand
```
Так запущенная команда в среде ipy вызывает системную команду pip, которая сама установит данный модуль в вашу виртуальную среду.

Обратите внимание, что каждый ноутбк имеет свой набор используемых библиотек и системных установок.


In [ ]:
!pip install numpy

## Подключение

Для подключения модулей в Python используется команда `import` или её вариации. В случае с numpy есть традиционная и привычная всем команда импорта с использованием алиаса (as) np

Алиас - это встроенная команда интерпретатора для сокращения команд и их последовательностей.

In [ ]:
# классический вариант
import numpy

In [ ]:
# традиционный вариант
import numpy as np

При таком импорте к любым командам из модуля numpy придётся дописывать название модуля

```
numpy.comand
np.comand
```
Есть другой вариант, в котором можно использовать только команду без указания модуля. Но так как в разных модулях могут быть одинаковые функции, использовать такой вариант не рекомендуется.


In [ ]:
from numpy import *

## Особые константы

Numpy реализует несколько особых значнений через контстанты. Например:

In [ ]:
np.NaN
# not a number - Не число

nan

In [ ]:
np.Inf
# infinity - бесконечность

inf

## Массивы

Главная особенность и элемент, с которым необходимо работать, в numpy - это массивы. Создаются массивы разными способами, которые мы сейчас разберём.

При этом всем элементы в array должны быть одного типа, что отличает его от классического списка (list) Python.

In [ ]:
a = np.array([1, 2, 3, 4], float)
print('Array:', a)
print('Тип: ',type(a))
# обратное преобразование
print(a.tolist())

Array: [1. 2. 3. 4.]
Тип:  <class 'numpy.ndarray'>
[1.0, 2.0, 3.0, 4.0]


In [ ]:
# показыаем, что можно также работать с np.array, как и с обычным list
a = np.array([1, 2, 4, 4])

print('1: ', a[0])
print('2: ', a[1:3])
print('3: ', a[-1])
a[0] = 5
print('4: ', a[0])

1:  1
2:  [2 4]
3:  4
4:  5


### Многомерные массивы

Большая ценность numpy в том, что можно работать и многомерными массивами. Например, любое изображение - как минимум двумерный массив. А при обучении нейронных сетей для работы с компьютерным зрением используются по сути четырёхмерные массивы.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]], int)
print(a)
print('1: ', a[0,0])
print('2: ', a[1,0])
print('3: ', a[0,1])

[[1 2 3]
 [4 5 6]]
1:  1
2:  4
3:  2


In [ ]:
# срезы (сленг - слайсы) с двмерным массивом
print('4: ', a[1,:])
print('5: ', a[:,2])
print('6: ', a[-1:, -2:])

4:  [4 5 6]
5:  [3 6]
6:  [[5 6]]


### Характеристики объектов numpy

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]], int)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
len(a)

2

In [ ]:
# размеры
a.shape

(2, 3)

In [ ]:
# тип данных внутри
# напоминаем, массив numpy может хранить только один тип данных
a.dtype

dtype('int64')

### Изменение размеров массива

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a = a.reshape(3,2)

In [ ]:
# обратите внимание, что в процессе изменения размера создан новый массив, а не изменён старый
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# с помощью этой команды можно вытянуть массив в одномерную "строку"
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [ ]:
# обратите внимание, что в процессе изменения размера создан новый массив, а не изменён старый
a

array([[1, 2],
       [3, 4],
       [5, 6]])

### Создание по-разному заполненных массивов

In [ ]:
# аналог range для массивов
print(np.arange(5))
print(np.arange(1, 6, 2))

[0 1 2 3 4]
[1 3 5]


In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# k - номер диагонали, заполненный единицами
np.eye(5,4, k=2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Перебор элементов массива

In [ ]:
a = np.array([1, 4, 5], int)

In [ ]:
# простой перебор для одномерного случая
for x in a:
   print(x)

1
4
5


In [ ]:
# простой перебор для многомерного случая срабаотает плохо, он перебирает по первой размерности
a = np.array([[1, 2], [3, 4], [5, 6]], float)
for x in a:
   print(x)

[1. 2.]
[3. 4.]
[5. 6.]


In [ ]:
# перебор правильным способом
for x in range(a.shape[0]):
  for y in range(a.shape[1]):
    print(a[x, y])

1.0
2.0
3.0
4.0
5.0
6.0


## Операции над массивами

### Математические операции над массивами

С массивами можно применять стандартные математические операции. Они будут работать так, как будето происходит поэлементая работа одной и той же операции. Для матричных операций есть специальные команды.

**Стандартные математические операции применимы только к массивам одинаковых размеров.**

In [ ]:
a = np.arange(1, 7, 1, dtype=int)
b = np.arange(6, 9, 1, dtype=int)
print('a: ', a)
print('b: ', b)

a:  [1 2 3 4 5 6]
b:  [6 7 8]


In [ ]:
a[3:] + b

array([10, 12, 14])

In [ ]:
a[3:] - b

array([-2, -2, -2])

In [ ]:
a[3:] * b

array([24, 35, 48])

In [ ]:
b / a

array([6.        , 3.5       , 2.66666667])

In [ ]:
a % b

array([1, 2, 3])

In [ ]:
b**a

array([  6,  49, 512])

In [ ]:
a // b

array([0, 0, 0])

Кроме того, поэлементно могут быть применены другие математические операции

In [ ]:
# корень
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [ ]:
a = np.array([1.1, 1.5, 1.9], float)

In [ ]:
# округление вниз
np.floor(a)

array([1., 1., 1.])

In [ ]:
# округление вврех
np.ceil(a)

array([2., 2., 2.])

In [ ]:
# округление по правилам математики
np.rint(a)

array([1., 2., 2.])

### Простые операции над массивами

#### Одномерные массивы

In [ ]:
a = np.arange(1, 6, 1)
print(a)
print('Сумма: ', a.sum())
print('Перемножение: ', a.prod())

[1 2 3 4 5]
Сумма:  15
Перемножение:  120


In [ ]:
# среднее (математическое ожидание)
a.mean()

3.0

In [ ]:
# дисперсия (смещенная - это будет важно в дальнейшем)
a.var()

2.0

In [ ]:
# стандартное отклонение (несмещенное - это тоже будет важно в дальнейшем)
a.std()

1.4142135623730951

In [ ]:
a.min()

1

In [ ]:
a.argmin()

0

In [ ]:
# clip позволяет "отрезать" значения сверху и снизу
a = np.array([6, 2, 5, -1, 0, 6, 2, 5, 4], float)
a.clip(0, 5)

array([5., 2., 5., 0., 0., 5., 2., 5., 4.])

In [ ]:
np.unique(a)

array([-1.,  0.,  2.,  4.,  5.,  6.])

#### Многомерные массивы
Для работы с многомерными массивами можно использовать параметр `axis`.

In [ ]:
a = np.array([[5, 2], [4, 1], [3, -1]])
print(a)
print(a.mean(axis=0))
print(a.mean(axis=1))
a.mean()

[[ 5  2]
 [ 4  1]
 [ 3 -1]]
[4.         0.66666667]
[3.5 2.5 1. ]


2.3333333333333335

### Логические операции над массивами

In [ ]:
a = np.array([1, 3, 0])
b = np.array([0, 3, 2])

print(a > b, type(a>b))

[ True False False] <class 'numpy.ndarray'>


In [ ]:
c = a > 2
c

array([False,  True, False])

In [ ]:
# проверяем, что хотя бы один элемент истинен
print(any(c))
# проверяем, что все элементы истинны
print(all(c))

True
False


Если вы хотите провести сравнение логическим И или логическим ИЛИ, то необходимо воспользоваться специальнымыми методами:


```
np.logical_and(_, _)
np.logical_or(_, _)
np.logical_not(_)
```



In [ ]:
(a < 3) * (a > 0)

array([[False,  True],
       [False,  True],
       [False, False]])

In [ ]:
np.logical_and(a > 0, a < 3)

array([ True, False, False])

С помощью `np.where` можно создать массив на основании условий.
Синтаксис:


```
where(boolarray, truearray, falsearray)
```



In [ ]:
a = np.array([1, 3, 0])
a

array([1, 3, 0])

In [ ]:
np.where(a != 0, 1 / a, a)

<ipython-input-37-02e1e0c5bd2e>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.where(a != 0, 1 / a, a)


array([1.        , 0.33333333, 0.        ])

Можно проверять элементы массива на наличие NaN и бесконечностей.

In [ ]:
a = np.array([1, np.NaN, np.Inf], float)
a

array([ 1., nan, inf])

In [ ]:
np.isnan(a)

array([False,  True, False])

In [ ]:
np.isfinite(a)

array([ True, False, False])

### Выбор элементов массива по условию

Очень важной особенностью массивов является то, что элементы в них можно брать на основании других массивов. Это особенно полезно при реализации свёрточных нейронных сетей.

In [ ]:
# это результат применения логической операции к многомерному массиву
a = np.array([[6, 4], [5, 9]], float)
a >= 6

array([[ True, False],
       [False,  True]])

In [ ]:
# а это результат фильтрации элементов
# обратите внимание, получился одномерный массив, содержащий только элементы, удовлетворяющие условию
a[a >= 6]

array([6., 9.])

In [ ]:
a[np.logical_and(a > 5, a < 9)]

array([6.])

Обратите внимание, что если передать целочисленные значения, в качестве условий, то результат будет другой. Будут выбраные соответствующие элементы.

In [ ]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2], int)
a[b]

array([2., 2., 4., 8., 6.])

In [ ]:
# Для выбора значений из многомерных массивов необходимо передать массивы, которые определяют индексы по каждому из направлений. Они должны быть, естественно, целочисленными.
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b,c]

array([ 1.,  4., 16., 16.,  4.])

## Векторная и матричная математика с использованием numpy

Векторная математика в numpy - это главная причина того, что numpy стал ключевым модулем Python среди всех представленных модулей. Векторные вычисления позволяют значительно ускорить обработку численной информации.

Часто сравнивая Python c С++/C говорят том, что первый гораздо менее производителен. Но с учётом современных модулей верно следующее утверждение: хорошо написанная программа на Python будет производительнее, чем средняя программа на C/C++, хорошую программу на C/C++ написать крайне сложно.

В дополнении к арифметически операциям мы рассмотрим некоторые векторные операции. Глубокое погружение в их суть требует значительных знаний математики, которые мы будем получать по мере необходимости.

### Скалярное произведение

Для двух векторов a и b одинаковой длины скалярное произведение считается по следующей формуле:

$ a*b = \sum_{i=0}^{len(a)}  a_i*b_i $

In [ ]:
# скалярное произвдение векторов, также операция свёртки в свёрточных нейронных сетях

a = np.array([1, 2, 3], float)
b = np.array([0, 1, 1], float)
np.dot(a, b)

5.0

### Произведение матриц

Произведение матриц - это особая математическая операция, которая не эквивалентна произведени соответствующих элементов матриц. О матричном произведении целесообразно говорить в рамках соответствующих разделов математики. Тем не менее, используя numpy легко получить матричное произведение.

In [ ]:
a = np.array([[0, 1], [2, 3]], float)
b = np.array([2, 3], float)
d = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]], float)

In [ ]:
np.dot(b, a)

array([ 6., 11.])

In [ ]:
np.dot(a, b)

array([ 3., 13.])

In [ ]:
a@b

array([ 3., 13.])

In [ ]:
# следите за размерностью, иначе ничего не получится
np.dot(b, d)

ValueError: ignored

### Определитель матриц

Многие математические операции, связанные с линейной алгеброй реализованы в модуле linalg внутри numpy. Мы не будем углулбляться в различные функциия модуля, рассмотрим для примера определитель.

In [ ]:
np.linalg.det(a)

-2.0

# Дополнительный материал для желающих

[Нескучный туториал по numpy](https://habr.com/ru/post/469355/)

# Задания

**Задача 1.**

Создать матрицу размером `10х10` с 0 внутри, и 1 на границах. Например для `3х3`.

```
1 1 1
1 0 1
1 1 1
```
Количество строк кода идеального решения: 2  
Кроме print()

In [1]:
import numpy as np
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**Задача 2.**

Создать 5x5 матрицу с 1,2,3,4 над диагональю. Все остальные элементы - 0.

Количество строк кода идеального решения: 1   
Кроме print()

In [13]:
import numpy as np
x = np.diag(np.arange(1, 5), k = 1)
print(x)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


**Задача 3.**

Дан массив, поменять знак у элементов, значения которых между 3 и 8.

In [12]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
n = np.where((arr > 3) & (arr < 8))
arr[n] =arr[n]*-1
print(arr)

[ 1  2  3 -4 -5 -6 -7  8  9 10]


**Задача 4.**

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением.

In [11]:
import numpy as np
arr = np.array([1,2,3,4,5])
n = 3
arr1 = np.zeros(len(arr) + (len(arr) - 1)*(n))
arr1[::n+1] = arr
print(arr1)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


**Задача 5.**

Дана матрица MxN. Поменять 2 любые строки в матрице.

In [6]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
x[[0,1]] = x[[1,0]]
print(x)

[[4 5 6]
 [1 2 3]
 [7 8 9]]


**Задача 6.**

Дан одномерный массив. Найти наиболее частое значение в массиве.

In [19]:
import numpy as np
arr = np.array([1, 2, 2, 3])
print(np.argmax(np.bincount(arr)))

2


**Задача 7.**

Дан массив 16x16, посчитать сумму по блокам 4x4.

In [21]:
import numpy as np
arr = np.random.randint(10,99,(16,16))
print(np.sum(arr[0:0+4,0:0+4]))
print(np.sum(arr[3:3+4,3:3+4]))
print(np.sum(arr[7:7+4,7:7+4]))
print(np.sum(arr[11:11+4,11:11+4]))

895
806
941
720


**Задача 8.**

Дана матрица. Найти n наибольших значений в массиве. n вводится с клавиатуры.

In [25]:
import numpy as np
n = int(input())
arr = np.array([1, 3, 2, 4, 5])
a = np.sort(arr)
l = a[len(a)-n:]
print(l)

[3 4 5]


**Задача 9.**

Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3]).

In [27]:
import numpy as np
arr = np.array([[9, 9, 9], [2, 2, 2], [4, 4, 4], [0, 0, 0], [1, 2, 1], [0, 0, 0], [0, 8, 0], [8, 4, 12], [3, 7, 0], [10, 10, 10]])
for i in range(arr.shape[0]):
    if arr[i].std() != 0:
        print(arr[i])

[1 2 1]
[0 8 0]
[ 8  4 12]
[3 7 0]


**Задача 10.**

Вектор A содержит float числа как больше, так и меньше нуля.

Округлите их до целых и результат запишите в переменную Z. Округление должно быть "от нуля", т.е.:

- положительные числа округляем всегда вверх до целого
- отрицательные числа округляем всегда вниз до целого
- 0 остаётся 0


In [28]:
import numpy as np
arr = np.array([2,3, -2,9, 0], float)
print(arr)
arr = np.where(arr > 0, np.ceil(arr), np.floor(arr))
print(arr)

[ 2.  3. -2.  9.  0.]
[ 2.  3. -2.  9.  0.]


**Задача 11.**

Даны 2 вектора целых чисел A и B.

Найдите числа, встречающиеся в обоих векторах и составьте их по возрастанию в вектор Z.

*Если пересечений нет, то вектор Z будет пустым*.

In [34]:
x = np.array([1, 5, 3])
y = np.array([4, 5, 6])
a = np.intersect1d(x, y, True)
print(a)

[5]


**Задача 12.**

Дан вектр. Найти максимальный элемент в векторе среди элементов, перед которыми стоит нулевой.

Например для:

`x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])`

Ответ:
5

In [35]:
arr = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
z = np.where(arr == 0)[0]
z = np.delete(z, np.where(z == len(arr) - 1))
print(np.max(arr[z + 1]))

5


**Задача 13.**

Дана матрица 5х3. Посчитать длинну каждого вектора в матрице (строка) и найти самый длинный ветор и вывести его координаты и длинну.

Как выглядит матрица:

```   
     | x | y | z |
     | 1 | 2 | 3 |
     | 3 | 4 | 1 |
     | ...       |
```